# PYTHON IMPLEMENTS FOUR DIFFERENT TYPES OF COLLECTIONS [ LISTS, TUPLES, SETS, DICTIONARY ]
# TUPLES : ORDERED AND UNCHANGEABLE
myTuple = ("AAA", "BBB", "CCC")
print(myTuple)

# ACCESSING SPECIFIC TUPLE MEMBER
print(myTuple[2])