# DIFFERENT FROM OTHER PROGRAM LANGUAGES PYTHON HAS NO SPECIFIC/RESERVED WORD FOR DECLARING A VARIABLE.
# A VARIABLE IS CREATED ONCE YOU FIRST ASSIGN A VALUE TO IT.

m = 10
n = "Stuart"

# VARIABLES DON'T NEED TO BE DECLARED WITH ANY PARTICULAR TYPE AND YOU CAN CHANGE TYPE.

# X IS OF TYPE INT
x = 4
print(type(x))

# X IS OF TYPE STRING
x = "Sally"
print(type(x))

# X IS OF TYPE FLOAT
x = 3.14
print(type(x))

# X IS OF TYPE COMPLEX
x = 1j
print(type(x))

# GENERAL RULES FOR VARIABLES
# (1) A VARIABLE NAME MUST START WITH A LETTER OR UNDERSCORE
# (2) A VARIABLE NAME CAN ONLY CONTAIN ALPHA-NUMERIC CHARACTERS ( A-z, 0-9, and _ )
# (3) VARIABLE NAME ARE CASE SENSITIVE (name, Name and NAME ARE DIFFERENT VARIABLES)

# CASTING : CAPABILITY TO SPECIFY A TYPE ON TO A VARIABLE
# TO CASTING IN PYTHON YOU CAN USE FUNCTIONS CONSTRUCTORS

# A WILL BE 10
a = int(10)
print(a)

# B WILL BE 2
b = int(2.8)
print(b)

# C WILL BE 3
c = int("3")
print(c)

# D WILL BE 1.0
d = float(1)
print(d)

# E WILL BE 4.75
e = float(4.75)
print(e)

# F WILL BE 9.0
f = float("9")
print(f)

# G WILL BE 2.2
g = float("2.2")
print(g)
