# PYTHON USES INDENTATION TO INDICATE BLOCKS OF CODE.
# PYTHON DON'T USE SEMICOLONS TO INDICATE END OF LINE.

if 1 == 1:
    print('[FIRST IF BLOCK]')
    print('[FIRST IF BLOCK]')
    if 2 == 2:
        print('[SECOND IF BLOCK]')
        print('[SECOND IF BLOCK]')
        if 3 == 3:
            print('[THIRD IF BLOCK]')
            print('[THIRD IF BLOCK]')
print('[OUTSIDE ALL IF BLOCKS]')

# NOTE: IF YOU SKIP INDENTATION YOU WILL SEE AN ERROR.
# YOU CAN CHECK THIS ERROR PUTTING AN IF CLAUSE FOLLOWED BY A PRINT CALL, AT SAME INDENTATION.
